### ISSUE TITLE
[GCC-11] GTE/Graphics/VisualEffect.cpp not compiled

### ISSUE THREAD

**Issue by sagitter** [davideberly/GeometricTools#6] opened 2020-12-20 15:49 UTC
Hello.

`gtengine-5.5` does not compile with `GCC-11.0.0` (i don't know if newer release of GCC is already supported):

```
[ 78%] Building CXX object Graphics/CMakeFiles/gtgraphics.dir/VisualEffect.cpp.o
cd /builddir/build/BUILD/GeometricTools-GTE-version-5.5/Graphics && /usr/bin/g++ -DGTE_DISABLE_PCH -DGTE_USE_LINUX -DGTE_USE_MAT_VEC -DGTE_USE_OPENGL -DGTE_USE_ROW_MAJOR -DNDEBUG -Dgtgraphics_EXPORTS -I/builddir/build/BUILD/GeometricTools-GTE-version-5.5/GTE/Graphics/.. -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNDEBUG -fPIC -c -Wall -Werror -O3 -std=c++14 -o CMakeFiles/gtgraphics.dir/VisualEffect.cpp.o -c /builddir/build/BUILD/GeometricTools-GTE-version-5.5/GTE/Graphics/VisualEffect.cpp
In file included from /usr/include/c++/11/string:40,
                 from /builddir/build/BUILD/GeometricTools-GTE-version-5.5/GTE/Graphics/../Graphics/DataFormat.h:10,
                 from /builddir/build/BUILD/GeometricTools-GTE-version-5.5/GTE/Graphics/../Graphics/VertexFormat.h:10,
                 from /builddir/build/BUILD/GeometricTools-GTE-version-5.5/GTE/Graphics/VertexFormat.cpp:9:
In function 'std::char_traits<char>::copy(char*, char const*, unsigned long)',
    inlined from 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy(char*, char const*, unsigned long)' at /usr/include/c++/11/bits/basic_string.h:351:21,
    inlined from 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)' at /usr/include/c++/11/bits/basic_string.tcc:481:20,
    inlined from 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::replace(unsigned long, unsigned long, char const*, unsigned long)' at /usr/include/c++/11/bits/basic_string.h:1946:19,
    inlined from 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::insert(unsigned long, char const*)' at /usr/include/c++/11/bits/basic_string.h:1714:22,
    inlined from 'std::operator+<char, std::char_traits<char>, std::allocator<char> >(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >' at /usr/include/c++/11/bits/basic_string.h:6154:23,
    inlined from 'gte::Logger::Logger(char const*, char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' at /builddir/build/BUILD/GeometricTools-GTE-version-5.5/GTE/Graphics/../Mathematics/Logger.h:86:44:
/usr/include/c++/11/bits/char_traits.h:402:56: error: 'memcpy' reading 6 bytes from a region of size 1 [-Werror=stringop-overread]
  402 |         return static_cast<char_type*>(__builtin_memcpy(__s1, __s2, __n));
      |                                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

Build log: https://kojipkgs.fedoraproject.org//work/tasks/6452/57876452/build.log

**Comment by davideberly** [comment] 2020-12-20 18:37
Thank you for reporting this. I will look into it.

According to gcc.gnu.org, GCC 11.0.0 is marked as “Development” and is not in the list of “Supported Releases.”

--
Dave Eberly
https://www.geometrictools.com

**Comment by davideberly** [comment] 2020-12-20 19:15
The VisualEffects.cpp file itself is not the problem. The error supposedly occurs because of inlining the constructor call for Logger. That code is
`Logger(char const* file, char const* function, int line, std::string const& message)`
`        {`
`            mMessage =`
`                "File: " + std::string(file) + "\n" +`
`                "Func: " + std::string(function) + "\n" +`
`                "Line: " + std::to_string(line) + "\n" +`
`                message + "\n\n";`
`        }`
Line 86, column 44 is within the call to `std::string(file)`. The constructor is called only through macros in Logger.h, where the `file` parameter is `__FILE__`, the `function` parameter is `__FUNCTION__` and the `line` parameter is `__LINE__`. It is not clear to me where this code is inlined; the header path in the error log does not suggest the location. Regardless, the compiler defines `__FILE__`, `__FUNCTION__` and `__LINE__`. The error says `memcpy` is trying to read 6 characters from a region with 1 character. I do not have a file with name of length 1, so I do not understand the error.

**Comment by davideberly** [comment] 2020-12-23 18:18
From the 'mock' shell for Fedora 34, I used the g++ compile command for VisualEffect.cpp as shown in your build logs, but with the include/source path modifications:

/usr/bin/g++ -DGTE_DISABLE_PCH -DGTE_USE_LINUX -DGTE_USE_MAT_VEC -DGTE_USE_OPENGL -DGTE_USE_ROW_MAJOR -DNDEBUG -Dgtgraphics_EXPORTS -I/home/GeometricTools/GTE/Graphics/.. -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNDEBUG -fPIC -c -Wall -Werror -O3 -std=c++14 -o VisualEffect.cpp.o -c /home/GeometricTools/GTE/Graphics/VisualEffect.cpp

No warnings or errors are generated.

**Comment by davideberly** [comment] 2021-01-15 19:38
Unless there is some guidance on how I can reproduce the problem (to be convinced it is my issue and not a compiler issue), I am closing this issue. Once Fedora 34 ships with GCC 11, if the issue persists, let me know. Thank you.

**Closed by davideberly** 2021-01-15 19:38 UTC

**Comment by sagitter** [comment] 2021-01-15 21:00
Hi David.

I can add that this is a known (unresolved) issue in Fedora; please, see bug ticket #[1909564](https://bugzilla.redhat.com/show_bug.cgi?id=1909564)
GCC-11 bug #[98465](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98465)

**Comment by davideberly** [comment] 2021-01-15 21:08
Hello Antonio.

Thank you. As the bug report indicates, this is a regression in the GCC-11 development.

--
Dave Eberly
https://www.geometrictools.com
